#!/bin/sh
alias ls='ls --color=auto'
alias l='ls'
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -lh'
alias lr='ll -R'
alias la='ls -lha'
alias lar='la -R'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias screen='screen -'
alias csvn='colorsvn'
alias svni='svn --ignore-externals'
alias csvni='csvn --ignore-externals'
alias svnvimdiff='svn diff --diff-cmd ~/bin/diffwrap.sh'
alias svnvimmerge='svn merge --diff3-cmd  ~/bin/diff3wrap.sh'
alias findsvn='find . -type d -name .svn'
alias rmsvn='rm -r `find . -type d -name .svn`'
alias rmsvnf='rmsvn -f' 
alias rmkeepsvn='rm -r `find . -not \( -name '.svn' -type d -prune \) -type f `'
alias rmkeepsvnf='rmkeepsvn -f' 
alias fromdosr='find . -type f \! -path "*svn*" -exec fromdos {} \;' 
alias todosr='find . -type f \! -path "*svn*" -exec todos {} \;' 
alias sc='screen -S charlie'
alias scdr='screen -dR charlie'
alias clr='clear'
alias du='du -h' 
alias dus='du -s' 
alias wanip='curl http://www.whatismyip.org/; echo "";'
alias df='df -hT --total'
