#!/bin/sh
alias ls='ls --color=auto'
alias l='ls'
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -lh'
alias lr='ll -R'
alias la='ls -lha'
alias lar='la -R'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias screen='screen -'
alias csvn='colorsvn'
alias findsvn='find . -type d -name .svn'
alias svni='svn --ignore-externals'
alias csvni='csvn --ignore-externals'
#alias svnvimdiff='svn diff --diff-cmd ~/bin/diffwrap.sh'
#alias svnvimmerge='svn merge --diff3-cmd  ~/bin/diff3wrap.sh'
alias rmsvn='rm -r `findsvn`'
alias rmsvnf='rmsvn -f'
alias sc='screen -S charlie'
alias scdr='screen -dR charlie'
alias clr='clear'
alias du='du -h'
alias dus='du -s'
alias df='df -hT --total'
